BookSystem/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("curd.urls"))
]

curd/urls.py
from django.urls import path

from . import views

app_name = 'curd'
urlpatterns = [
    path("", views.create_book, name="book"),
    path('view/<int:id>', views.view_book, name='view_book'),
    path('<int:id>', views.delete_book, name='delete'),
    path('edit/<int:id>', views.edit_book, name='edit_book'),
]

curd/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    book_name = models.CharField(max_length=100)
    book_description = models.TextField(blank=True)
    year_published = models.DateField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=60, blank=True)
    publish = models.BooleanField(default=True)

    def __str__(self):
        return self.book_name

curd/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['book_name', 'book_description', 'year_published', 'author']

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

curd/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .forms import BookForm
from .models import Book

# Create your views here.


# this is the curd operation
def create_book(request):
    book = Book.objects.all().order_by('-created_date')
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('curd:book')
    else:
        form = BookForm()
    context = {'form': form, 'book': book}
    return render(request, 'create.html', context)


def view_book(request, id):
    book = Book.objects.get(id=id)
    context = {'book': book}
    return render(request, 'view.html', context)


def edit_book(request, id):
    book = get_object_or_404(Book, id=id)
    if request.method == 'POST':
        form = BookForm(instance=book, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('curd:book')
    else:
        form = BookForm(instance=book)

    return render(request, "edit.html", {"form": form, "book": book})


def delete_book(request, id):
    book = Book.objects.get(id=id)
    book.delete()
    return redirect('curd:book')

curd/templates/create.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 py-2">
            <h1>Create Book and View</h1>
        </div> 
        <div class="col-md-8 mb-4 py-2 px-3">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">List of All Books</h4>
                    <table class="table-responsive table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Book Name</th>
                                <th>Edition Year</th>
                                <th>Created Date</th>
                                <th>Author</th>
                                <th>View/Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for list in book %}
                                <tr>
                                    <td>{{list.book_name}}</td>
                                    <td>{{list.year_published|date:'d/M/Y'}}</td>
                                    <td>{{list.created_date|date:'d/M/Y'}}</td>
                                    <td>{{list.author}}</td>
                                    <td>
                                        <a class="btn btn-outline-success" href="{% url 'curd:view_book' list.id %}" class="text-success"> 
                                            <i class="fa fa-eye-slash"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-outline-danger" href="{%  url 'curd:delete' list.id %}">     
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4 py-2 px-3">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Create Books</h4>
                    <form method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>       
    </div>
</div>

{% endblock content %}

curd/templates/delete.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Delete Book</h1>
            <form method="post">
                {% csrf_token %}
                <p>Are you sure delete this book <input type="sbumit" value= "confirm">  </p>
            </form> 
        </div>
    </div>
</div>

{% endblock content %}

curd/templates/edit.html
{% extends 'index.html' %} {% block content %}
<div class="container py-5">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Edit Books</h4>
          <form method="post">
            {% csrf_token %} {{form.as_p}}
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

curd/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<title>Book</title>
</head>
<style>
    body{
        background-color: #ccc;
    }
    .card{
        background-color: #fafafa;
        box-shadow: 0 0 10px #ccc;
    }
</style>

<body>

{% block content  %}

{% endblock  %}



<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
</body>
</html>

curd/templates/view.html
{% extends 'index.html' %}

{% block content %}
<div class="container py-5 mt-5">
    <div class="row">
        <div class="col-md-8 mb-4 py-2 px-3">
            <div class="card bg-light">
                <div class="card-body">
                    <h1 class="card-title">{{book.book_name}}</h1>
                    <p class="card-text">
                        {{book.book_description}}
                    </p>
                    <h6 class="bg-dark text-white">
                        Author: {{book.author}} | Edition: {{book.year_published|date:'d/M/Y'}}
                    </h6>
                </div>
                <div class="card-footer">
                    <div class="row d-flex align-items-center text-center">
                        <div class="col-md-4 col-sm-4 col-xm-4">
                            <div class="text-center text-dange">
                                Create Date: {{book.created_date|date:'d/M/Y'}} 
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xm-4">
                            <a class="btn btn-outline-success" href="{% url 'curd:edit_book' book.id %}" class="text-success"> 
                                <i class="fas fa-edit fa-lg fa-fw"></i>
                            </a>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xm-4">
                            <a class="btn btn-outline-danger" href="{%  url 'curd:delete' book.id %}">     
                                <i class="fa fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
        <div class="col-md-4 mb-4 py-2 px-3">
            <div class="card border-2">
                <img src="https://picsum.photos/200" alt="" class="img-card-top">
            </div>
        </div>   
    </div>
</div>

{% endblock content %}